### PR TITLE
A Simplified Chinese translation of the "dumbing-down-iterator" section

### PR DESCRIPTION
**Pull request by yshngg**
Your blog has been very helpful for me as a Rust beginner. I have translated one of the articles into Simplified Chinese, hoping it can help more Rust beginners or others. If you can accept my Pull Request, I will continue to translate two more blog posts into Chinese, and I will also do Chinese translations for your future blogs. I really appreciate it.

### CODE REVIEW

**Comment by alexpusch** [comment]
Hi @yushengguo557, glad to hear the post was helpful. Awesome work on the translation! I think it would be a better idea if you keep the translated version maintained under your own account, and I'll link to it from both the main Readme and the post Readmes. 

This way you'll have full control over the translated version.

what do you think?

**Comment by yshngg** [comment]
Thank you so much for replying to me🙇‍, your idea is really great. Then I will translate the remaining two articles into simplified Chinese versions, and hope you can link them in the Realme file. Thank you again😊.

**Comment by alexpusch** [comment]
@yushengguo557 I'm ok putting the links before you translate the rest of the posts. Tell me when you're ready and I'll put it. I just ask you to put links back here as well :slightly_smiling_face:

**Comment by yshngg** [comment]
I appreciate your response😊. Sure!

This is the Readme file for the rust-magic-patterns project: 
https://github.com/yushengguo557/rust-magic-patterns/blob/translation-zh-cn/Readme_ZH_CN.md

- rust-stream-visualized: 
https://github.com/yushengguo557/rust-magic-patterns/blob/translation-zh-cn/rust-stream-visualized/Readme_ZH_CN.md

- dumbing-down-iterator: 
https://github.com/yushengguo557/rust-magic-patterns/blob/translation-zh-cn/dumbing-down-iterator/Readme_ZH_CN.md

- axum-style-magic-function-param: 
https://github.com/yushengguo557/rust-magic-patterns/blob/translation-zh-cn/axum-style-magic-function-param/Readme_ZH_CN.md

Thank you for taking the time to put those links🙇‍.

**Comment by alexpusch** [comment]
@yushengguo557 could you please add links back to this repo?

**Comment by yshngg** [comment]
I'm sorry, I don't quite understand what you mean. Do you need me to add those links to the repository and submit a PR?😭

**Comment by alexpusch** [comment]
I just ask that if I add links to your translation to my posts, you'll add links to my posts in your translation :slightly_smiling_face:

**Comment by yshngg** [comment]
Okay, I have added the repository link now. Are there any other requirements? 😊

**Comment by alexpusch** [comment]
I've added the links to the main Readme and the posts. Thanks @yushengguo557 !

**Pull request closed without merging**
